<!--#include file="../../../../OVATION.INC"-->

<HTML>
<HEAD>
  <META NAME="Author" CONTENT="AST Computers, Inc.">
</HEAD>
<BODY BGCOLOR="#FFFFFF" LINK="#00698C" VLINK="#3A4D52" ALINK="#FFA600">
<TABLE WIDTH="570" CELLPADDING="10" CELLSPACING="0" BORDER="0">
<TR>
<TD VALIGN="TOP" WIDTH="696%"><P><IMG SRC="images/ms_5200.GIF" WIDTH="387" HEIGHT="128" ALIGN="BOTTOM"
NATURALSIZEFLAG="3" BORDER="0"></P>

<P>&nbsp;</P>

<P><B><I><BIG>Bravo MS 5200 Windows NT systems</BIG></I></B><BR>
<TABLE WIDTH="565" HEIGHT="347" BORDER="2" CELLSPACING="2" CELLPADDING=
"2">
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT>Model</TH>
<TD ALIGN="CENTER" BGCOLOR="#790f00"><B><FONT COLOR="#ffffff">2000C/NT</FONT></B></TD>
<TD BGCOLOR="#790f00"><P><CENTER><B><FONT COLOR="#ffffff">3000C/NT</FONT></B></CENTER></TD>
<TD BGCOLOR="#790f00"><P><CENTER>&nbsp;<B><FONT COLOR="#ffffff">3000C/NT</FONT></B></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Part&nbsp;# 503xxx-xxx</FONT></TH>
<TD ALIGN="CENTER"><SMALL>248-501</SMALL></TD>
<TD><P><CENTER><SMALL>248-301</SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL>251-301</SMALL></CENTER></TD></TR>

<% if session("source") = "ast" then %>

<% PriceLevelCode = "1" %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Level 1</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-501")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-301")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-301")%></SMALL></CENTER></TD></TR>

<% PriceLevelCode = "C" %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Level C</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-501")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-301")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-301")%></SMALL></CENTER></TD></TR>

<% PriceLevelCode = "G" %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Est. Street Price</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-501")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-301")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-301")%></SMALL></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Employee Purchase Price</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=EmployeePurchasePrice("503248-501")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=EmployeePurchasePrice("503248-301")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=EmployeePurchasePrice("503251-301")%></SMALL></CENTER></TD></TR>

<% elseif session("source") = "ovation" then %>

<% call GetPriceLevel %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000"><%=PriceLevelName%></FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-501")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-301")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-301")%></SMALL></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Government/Educational Rebate</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartRebate("503248-501")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartRebate("503248-301")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartRebate("503251-301")%></SMALL></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Demo Unit Purchase Price</FONT></TH>
<TD ALIGN="CENTER"><SMALL><A HREF="../../../sales_tools/demo_units/form.asp?pn=503248-501"><IMG SRC="images/tag.gif" BORDER=0></A><%=RealPartPrice("503248-501", "C", 0.85)%></SMALL></TD>
<TD><P><CENTER><SMALL><A HREF="../../../sales_tools/demo_units/form.asp?pn=503248-301"><IMG SRC="images/tag.gif" BORDER=0></A><%=RealPartPrice("503248-301", "C", 0.85)%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><A HREF="../../../sales_tools/demo_units/form.asp?pn=503251-301"><IMG SRC="images/tag.gif" BORDER=0></A><%=realPartPrice("503251-301", "C", 0.85)%></SMALL></CENTER></TD></TR>

<% end if %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Processor</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>Pentium 200Mhz</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Cache</FONT></TH>
<TD COLSPAN="3"><P><CENTER>&nbsp;<SMALL>512KB</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">RAM</FONT></TH>
<TD COLSPAN="3"><P><CENTER>&nbsp;<SMALL>32 MB</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="48" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Ultra DMA Hard Drive</FONT></TH>
<TD><P><CENTER><SMALL>2GB</SMALL></CENTER></TD>
<TD COLSPAN="2"><P><CENTER><SMALL>&nbsp;3 GB</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="48" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Synchronous Graphics RAM</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>2 MB (6 MB max)</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">CD-ROM</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>16x max</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Operating System</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>Windows NT</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Form Factor</FONT></TH>
<TD COLSPAN="2"><P><CENTER><SMALL>&nbsp;Desktop Case</SMALL></CENTER></TD>
<TD>&nbsp;<SMALL>&nbsp;MiniTower</SMALL></TD></TR>
</TABLE>
</P>

<P>&nbsp;</P>

<P><B><I><BIG>Bravo MS 5200 Windows 95 systems</BIG></I></B><BR>
<TABLE WIDTH="565" HEIGHT="347" BORDER="2" CELLSPACING="2" CELLPADDING=
"2">
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT>Model</TH>
<TD ALIGN="CENTER" BGCOLOR="#790f00"><B><FONT COLOR="#ffffff">2000C/95</FONT></B></TD>
<TD BGCOLOR="#790f00"><P><CENTER><B><FONT COLOR="#ffffff">3000C/95</FONT></B></CENTER></TD>
<TD BGCOLOR="#790f00"><P><CENTER>&nbsp;<B><FONT COLOR="#ffffff">3000C/95</FONT></B></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Part&nbsp;# 503xxx-xxx</FONT></TH>
<TD ALIGN="CENTER"><SMALL>248-101</SMALL></TD>
<TD><P><CENTER><SMALL>248-401</SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL>251-401</SMALL></CENTER></TD></TR>

<% if session("source") = "ast" then %>

<% PriceLevelCode = "1" %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Level 1</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-101")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-401")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-401")%></SMALL></CENTER></TD></TR>

<% PriceLevelCode = "C" %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Level C</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-101")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-401")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-401")%></SMALL></CENTER></TD></TR>

<% PriceLevelCode = "G" %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Est. Street Price</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-101")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-401")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-401")%></SMALL></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Employee Purchase Price</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=EmployeePurchasePrice("503248-101")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=EmployeePurchasePrice("503248-401")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=EmployeePurchasePrice("503251-401")%></SMALL></CENTER></TD></TR>

<% elseif session("source") = "ovation" then %>

<% call GetPriceLevel %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000"><%=PriceLevelName%></FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartPrice("503248-101")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartPrice("503248-401")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartPrice("503251-401")%></SMALL></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Government/Educational Rebate</FONT></TH>
<TD ALIGN="CENTER"><SMALL><%=PartRebate("503248-101")%></SMALL></TD>
<TD><P><CENTER><SMALL><%=PartRebate("503248-401")%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><%=PartRebate("503251-401")%></SMALL></CENTER></TD></TR>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Demo Unit Purchase Price</FONT></TH>
<TD ALIGN="CENTER"><SMALL><A HREF="../../../sales_tools/demo_units/form.asp?pn=503248-101"><IMG SRC="images/tag.gif" BORDER=0></A><%=RealPartPrice("503248-101", "C", 0.85)%></SMALL></TD>
<TD><P><CENTER><SMALL><A HREF="../../../sales_tools/demo_units/form.asp?pn=503248-401"><IMG SRC="images/tag.gif" BORDER=0></A><%=RealPartPrice("503248-401", "C", 0.85)%></SMALL></CENTER></TD>
<TD><P><CENTER>&nbsp;<SMALL><A HREF="../../../sales_tools/demo_units/form.asp?pn=503251-401"><IMG SRC="images/tag.gif" BORDER=0></A><%=realPartPrice("503251-401", "C", 0.85)%></SMALL></CENTER></TD></TR>

<% end if %>

<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Processor</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>Pentium 200Mhz</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Cache</FONT></TH>
<TD COLSPAN="3"><P><CENTER>&nbsp;<SMALL>512KB</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">RAM</FONT></TH>
<TD COLSPAN="3"><P><CENTER>&nbsp;<SMALL>32 MB</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="48" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Ultra DMA Hard Drive</FONT></TH>
<TD><P><CENTER><SMALL>2GB</SMALL></CENTER></TD>
<TD COLSPAN="2"><P><CENTER><SMALL>&nbsp;3 GB</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="48" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Synchronous Graphics RAM</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>2 MB (6 MB max)</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">CD-ROM</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>16x max</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Operating System</FONT></TH>
<TD COLSPAN="3"><P><CENTER><SMALL>Windows NT</SMALL></CENTER></TD></TR>
<TR ALIGN="CENTER">
<TH ALIGN="LEFT" HEIGHT="28" BGCOLOR="#fff4f2"><P ALIGN=LEFT><FONT COLOR="#000000">Form Factor</FONT></TH>
<TD COLSPAN="2"><P><CENTER><SMALL>&nbsp;Desktop Case</SMALL></CENTER></TD>
<TD>&nbsp;<SMALL>&nbsp;MiniTower</SMALL></TD></TR>
</TABLE>
</P>

<P>&nbsp;</P>

<P>&nbsp;</P>

<P>&nbsp;</TD></TR>
</TABLE>
</BODY>
</HTML>
