<html><head>
<title>ASC Handbook</title>
</head>
<body bgcolor='ffffff' text='000000' LINK="#0000FF" ALINK="#0000FF" VLINK="#0000FF"><b>
Pronto! Pro <i>OnLine</I> Text Version
<CENTER>
<!-- #INCLUDE FILE="TITLE.INC" -->
</CENTER>
<P>
<CENTER><h2>Select country</h2></CENTER>
<TABLE WIDTH=100% BORDER=0 CELLSPACING=0 CELLPADDING=0>
  <TR>
	<TD ALIGN=CENTER><H3><A HREF="asc/caindex.asp">Canada</A></H3></TD>
	<TD ALIGN=CENTER><H3><A HREF="ASC/USAINDEX.asp">United States</A></H3></TD>
	<TD ALIGN=CENTER><H3><A HREF="asc/laindex.asp">Latin America</A></H3></TD>
	<TD ALIGN=CENTER><H3><A HREF="asc/euindex.asp">Europe</A></H3></TD>
  </TR>
</table>
<HR>
<CENTER>
<h3>ASC Handbook</h3>
<H4> NOTICE </H4><hr>
</center><FONT SIZE='2'>
<b>THE INFORMATION CONTAINED IN THIS HANDBOOK
IS SUBJECT TO CHANGE WITHOUT NOTICE. AST RESEARCH, INC., SHALL
NOT BE LIABLE FOR TECHNICAL OR EDITORIAL ERRORS OR OMISSIONS
CONTAINED HEREIN; NOR FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES
RESULTING FROM THE FURNISHING, PERFORMANCE, OR USE OF THIS
MATERIAL. </b>

<p>This document contains copywritten and proprietary
information protected by copyright. All rights are reserved. No
part of this document may be photocopied or reproduced in any
form without prior written consent from AST Research, Inc.
Unauthorized reproduction, distribution and/or sale may result in
imprisonment of up to one year and a fine of up to $10,000.
Copyright infringement may result in civil liability.
</FONT>
<BR><BR><BR>
</body>
</html>
