<html><head>
<title>Pronto Pro! Home Page</title>
<body bgcolor='ffffff' text='000000' LINK="#0000FF" ALINK="#0000FF" VLINK="#0000FF">

<b>Pronto! Pro <i>OnLine</I> Text Version</b>
<CENTER>
<!-- #INCLUDE FILE="TITLE.INC" -->
</CENTER>


<P>
<h2>Legal Stuff</h2>

<p ALIGN="justify">AST and Advantage! are registered trademarks and
AST Computer, the AST logo, Manhattan, Premmia, Pronto! Pro are
trademarks of AST Research, Inc. All other product or service
names mentioned herein may be trademarks or registered trademarks
of their respective owners. The information in this document and
contained in this web page is subject to change without notice.
No part of this document or contents of the Pronto! Pro web pages
may be reproduced or transmitted in any form or by any means,
electronic or mechanical, for any purpose, without the express
written permission of AST Research, Inc. AST Research, Inc shall
not be liable for technical or editorial errors or omission; nor
for incidental or consequential damages resulting from the
furnishing, performance or use of this material. </p>


<p align="center">Copyright © 1990-97 AST Research, Inc All
Rights Reserved <br><br><br><br>
<%
 Set MyPageCount = Server.CreateObject("IISSample.PageCounter")
 HitMe = MyPageCount.Hits
%>
<p>
<center>
<br><br>
<i>This page has was last updated October 27 1997</i>
</center>
</body>
</html>
