<html><head>

<title>Pront! Pro Feedback Page</title>
</head>

<body bgcolor='ffffff' text='000000' LINK="#0000FF" ALINK="#0000FF" VLINK="#0000FF"><b>
Pronto! Pro <i>OnLine</I> Text Version
<CENTER>
<!-- #INCLUDE FILE="TITLE.INC" -->
</CENTER>
<P>
<h2 align="center">Comments / Suggestions</h2>

<hr>

<h4>To deliver the best possible tool, we need the help of our
users. Please send any comments, suggestions, or corrections to: </h4>

<table border="0" width="100%">
    <tr>
       <td valign="top"><p align="center">
        <b>Attention Team Pronto! <br>
        AST Research - Department 682 <br>
        16215 Alton Parkway - MS 3-52 <br>
        Irvine, CA 92718 </b></p>
        </td>
        <td valign="top"><p align="center"><a
        href="mailto:pronto@ast.com"><b><br>
        Click here to E-mail Team Pronto! <br>
        </b><b><i>Pronto@ast.com </i></b></a><br>
        <br>
        </p>
        </td>
    </tr>
</table>
</body>
</html>
