<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1252">
<META NAME="Generator" CONTENT="Microsoft Word 97">
<TITLE>Pronto</TITLE>
</HEAD>
<body bgcolor='ffffff' text='000000' LINK="#0000FF" ALINK="#0000FF" VLINK="#0000FF"><b>
Pronto! Pro <i>OnLine</I> Text Version
<CENTER>
<!-- #INCLUDE FILE="TITLE.INC" -->
</CENTER>
<P>
<B><H1>Pronto!Pro <I>Online</H1>
<BR><H3>Quick Start Handbook</I></B></H2>

<DL>
    <DT> <A HREF="#Introduction"> Introduction</A>
    <DT> <A HREF="#MainMenu"> Main Menu Bar</A>
    <DD> <A HREF="#Products"> Products</A>   
    <DD> <A HREF="#BIOS"> BIOS Tables</A>
    <DD> <A HREF="#ASC"> ASC Handbook</A>
    <DD> <A HREF="#TechRef"> Tech Ref</A>
    <DD> <A HREF="#News"> News</A>
    <DD> <A HREF="#Tools"> Tools</A>
    <DD> <A HREF="#feedback"> Feedback</A>
    <DT> <A HREF="#steps"> Step By Step Instructions</A>
    <DT> <A HREF="#map"> Appendix A. Site Map</A>
</DL>


<A NAME="Introduction"><STRONG></STRONG></A>

<B><U><P>a. Introduction</P><DIR>


</B></U><P>Welcome to the next generation of <B>Pronto!Pro:</B> <B>Pronto!Pro</B><I>Online,</I> the complete AST product information tool, now accessible over the internet, worldwide, 24 hours a day. This document will be your quick start guide and reference manual for using the new <B>Pronto!Pro</B><I>Online </I>system efficiently, and at the greatest ease possible. Although <B>Pronto!Pro</B><I>Online</I> was written to be as simple as possible, it is suggested you read this document for a general overview of all of its features and components.</P>
<P>&nbsp;</P></DIR>

<B><U><P>1. Overview/Interface Tutorial</P><DIR>


</B></U><P>Pronto!Pro Online is the new World Wide Web adapted version of AST’s standard product support and information tool, <B>Pronto!Pro.</B> This new online version has been created with ease in mind, as well as efficient use. The interface itself, has been modeled after Microsoft Windows and its file system, the <I>explorer</I>. Through the use of this <I>explorer</I> interface, files and information are handled in <I>folders </I>in a hierarchy tree form. To gain access to any information you may be looking for, you simple break the tree down by clicking on the folders named in relationship to that information. </P></DIR>

<B><P>Ex 1.</B> <B>Simple Information Retrieval :</B> Customer wants information on – 17" 7L Monitor.</P><DIR>
<DIR>
<DIR>
<DIR>

<B><P>Step 1.)</B> &#9;Select the <I>Products</I> icon from the <B>Menu Bar</B> on the <B>Pronto!Pro</B><I>Online</I> homepage.</P>
<B><P>Step 2.)</B> &#9;Narrow your search by selecting the <I>Monitors </I>icon from left-hand frame in your browser.</P>
<B><P>Step 3.) &#9;</B>Narrow your search a bit more by selecting <I>17" Monitors</I> from the expanded folder tree.</P>
<B><P>Step 4.) &#9;</B>Finally, you may select the 7L monitor that suites your customers needs from the list of available 17" monitors on the right-hand frame of your browser.</P></DIR>
</DIR>
</DIR>
</DIR>

<B><P>Note: More <U>examples</U> are avaliable for each section of Pronto!Pro</B><I>Online</P>
</I><P>&nbsp;</P>

<A NAME="MainMenu"><STRONG></STRONG></A>


<B><U><P>2. Main Menu Bar</P><DIR>

</B></U><P>The Menu bar of Pronto!Pro Online contains 8 main icons which operate similar to any other icon on your browsers various other toolbars. <B><U>Products</B></U>, <B><U>BIOS</B></U>, <B><U>ASC</B></U>, <B><U>Tech Ref</B></U>, <B><U>News</B>,</U> <B><U>Help</B>, <B>Tools</B></U>, and <B><U>Feedback</B></U>. Each button is a link to a separate section of the <B>Pronto!Pro</B><I>Online</I> System. The Buttons work as followed:</P>

<A NAME="Products"><STRONG></STRONG></A>

<B><U><P>a. Products</P><DIR>

</B></U><P>The products section is the core functionality of the New <B>Pronto!Pro</B><I>Online </I>system. By clicking on the <I>Products</I> Icon, the left-hand frame of your browser will be filled with a top down heiarchy view of AST’s entire product line including systems and monitors, in one easy to use visual tree. This <I>tree </I>is organized and built with the functionality to emulate the windows 95 explorer interface. By simply clicking on the folder of your choice the tree <I>explodes</I> to reveal its contents, and by repeating this action you can narrow your search to any product you may be searching for.</P></DIR>

<A NAME="BIOS"><STRONG></STRONG></A>

<B><U><P>b. BIOS Tables</P><DIR>
<DIR>

</B></U><P>By clicking the <I>BIOS<B> </B></I>icon, you are brought into the BIOS Table section of <B>Pronto!Pro</B><I>Online</I>. Much like the <I>Products</I> section, the left-hand frame is modeled after the windows 95 explorer, and reacts in the same general way. By clicking on the product line of which BIOS you are in search of, the right-hand frame will fill with a quick reference table of BIOS files available for that product line. By clicking on the filename in the "<I>BIOS Update File</I>" field of the product BIOS table you will be prompted to download that BIOS file to your local hard disk drive.</P></DIR>
</DIR>

<A NAME="ASC"><STRONG></STRONG></A>

<B><U><P>c. ASC Handbook</P><DIR>

</B></U><P>By clicking on the <I>ASC</I> button in the main menu bar, your left-hand browser frame will change to a tree of folders each entitled to a corresponding regions, and each containing the full text in PDF format of the AST ASC Handbook for that country. Simply click on your regions title to download the ASC Handbook to your local hard disk drive.</P></DIR>

<A NAME="TechRef"><STRONG></STRONG></A>

<B><U><P>d. Technical Reference</P><DIR>

</B></U><P>The <I>Tech Ref</I> icons leads you into the AST Technical Reference section of www.ast.com. Just click on one of the three icons in the left-hand frame of your browser, and you will be directly linked in to all of your AST bulletin needs.</P></DIR>

<A NAME="News"><STRONG></STRONG></A>

<B><U><P>e. News</P><DIR>

</B></U><P>The <I>News</I> icon leads you to a simple view of all news bulletins relating to <B>Pronto!Pro</B><I>Online</I> and its continual development and additions.</P></DIR>

<A NAME="Tools"><STRONG></STRONG></A>

<B><U><P>f. Tools</P><DIR>

</B></U><P>The <I>Tools</I> icon leads you into the software tools and links section of <B>Pronto!Pro</B><I>Online<B>. </B></I>Within this section you can download just about any tool you may need for navigating around the web based version of <B>Pronto!Pro</B><I>.</I> This section of <B>Pronto!Pro</B><I>Online </I>also contains links to popular hardware and software vendor homepages in which may have other useful information related to AST product support. </P></DIR>

<A NAME="Help"><STRONG></STRONG></A>

<B><U><P>g. Help</P><DIR>

</B></U><P>You’re looking at it. Come here for help, tutorials, tips, general information, future news, a glossary, and the site map for <B>Pronto!Pro</B><I>Online.</P></DIR>

<A NAME="feedback"><STRONG></STRONG></A>

</I><B><U><P>h. Feedback</P><DIR>

</B></U><P>Select the Feedback icon of the <B>Pronto!Pro</B><I>Online</I> menu bar to submit all comments regarding <B>Pronto!Pro</B><I>Online</I>, it’s bugs, ideas for it’s further development, or just senseless praise to its wonderful creators for making your life so much simpler.</P>
<P>&nbsp;</P></DIR>
</DIR>

<OL START=2>

<A NAME="steps">

<B><U><P><LI>Step by Step instructions</LI></P></OL></A>

</B></U><P>&nbsp;</P>
<OL>

<B><P><LI>Products</LI></P>
<P>Example, Simple Information Retrieval :</B> Customer wants information on – 17" 7L Monitor.</P>
<B><P>Step 1.)</B> &#9;Select the <I>Products</I> icon from the <B>Menu Bar</B> on the <B>Pronto!Pro</B><I>Online</I> homepage.</P>
<B><P>Step 2.)</B> &#9;Narrow your search by selecting the <I>Monitors </I>icon from left-hand frame in your browser.</P>
<B><P>Step 3.) &#9;</B>Narrow your search a bit more by selecting <I>17" Monitors</I> from the expanded folder tree.</P>
<B><P>Step 4.) &#9;</B>Finally, you may select the 7L monitor that suites your customers needs from the list of available 17" monitors on the right-hand frame of your browser.</P>
<P>&nbsp;</P>
<B><P><LI>BIOS Tables</LI></P>
<P>Example, Downloading BIOS :</B> You need to download the bios for Bravo MS-166 (503418).</P>
<B><P>Step 1.)</B> &#9;Select the <I>BIOS</I> icon from the <B><U>Menu Bar</B></U> on the <B>Pronto!Pro</B><I>Online</I> homepage.</P>
<B><P>Step 2.) &#9;</B>Narrow your search by selecting the type of system BIOS from the left-hand frame of your browser. This will align the right-hand frame to the section of BIOS you selected. In this case, the selection would be <B><U>Bravo</B></U>.</P>
<B><P>Step 3.) &#9;</B>Now drag the right-hand frame to the matching row of the BIOS table matching your needs. Drag the table until you reach <B>503418, Bravo MS-166.</P>
<P>Step 4.)</B>&#9;Next click the filename** in the far right cell of the current row to download your BIOS file. In this case - <B>05606036.EXE</P>
<P>Step 5.)&#9;</B>Uncompress the file by executing it to an empty directory, and read any further instructions contained within.</P>
<P>** note: All BIOS filenames will end with <I>.EXE</I>.</P>
<P>&nbsp;</P>
<B><P><LI>ASC Handbook</LI></P>
<P>Step 1.)</B> &#9;Follow instructions contained on page.</P>
<P>&nbsp;</P>
<B><P><LI>Technical Reference</LI></P>
<P>Example, Tech. Reference Bulletin :</B> You want to see all AST hardware technical bulletins.</P>
<B><P>Step 1.)</B> &#9;Select the <I>Tech Ref</I> from the <B>Menu Bar</B> on the <B>Pronto!Pro</B><I>Online</I> homepage.</P>
<B><P>Step 2.)</B>&#9;Select the type of bulletin (<I>hardware</I>) you’re looking for in the left-hand frame of your browser. This will fill the right-hand frame of your browser with all AST bulletins relating to your choice.</P>
<B><P>Step 3.)&#9;</B>Select any individual <B><U>htm</B></U> bulletin file from the right-hand window to view its contents. </P>
<P>&nbsp;</P>
<B><P><LI>News</LI></P>
<P>Example, News Reference :</B> You want to see all <B>Pronto!Pro</B><I>Online </I>related news.</P>
<B><P>Step 1.)</B> &#9;Select the <I>News</I> from the <B>Menu Bar</B> on the <B>Pronto!Pro</B><I>Online</I> homepage.</P>
<B><P>Step 2.)</B>&#9;Select the type of News you’re looking for in the left-hand frame of your browser. In this case <B>Pronto!Pro</B> news.</P>
<B><P>Step 3.)&#9;</B>Browse through the right-hand frame to read all updated <B>Pronto!Pro</B><I>Online</I> news. </P>
<P>&nbsp;</P>
<B><P><LI>Tools</LI></P>
<P>Example, Tool Download :</B> You want to download a viewer of PDF (Acrobat) files.</P>
<B><P>Step 1.)</B> &#9;Select the <I>Tools</I> from the <B>Menu Bar</B> on the <B>Pronto!Pro</B><I>Online</I> homepage.</P>
<B><P>Step 2.)</B>&#9;Select the type of tool you are looking for in the left-hand frame’s tree of your browser, or drag down the list of descriptions on the right-hand frame. In this case<B> </B>we’re looking for Software/Viewers/Acrobat.</P>
<B><P>Step 3.)&#9;</B>By clicking on the link, you will be brought to the software companies download section where you can download the file specifically for your system.</P>
<B><P>Step 4.)</B>&#9;Follow instructions given by software tool vendor.</P>
<P>&nbsp;</P>
<B><P><LI>Help</LI></P></OL>
<DIR>
<DIR>

<P>Example, Help :</B> You want to get help!</P>
<B><P>Step 1.)</B> &#9;Read. </P></DIR>

<P>&nbsp;</P></DIR>

<A NAME="map"><STRONG></STRONG></A>

<B><U><P>Appendix A. Pronto!Pro</B><I>Online </I><B>Site Map</P>

</U><P>Products</P><DIR>
<DIR>

</B><P><A HREF='SYSMNU.asp'>Advantage!</A></P>
<P><A HREF='SYSMNU.asp'>Portable</A></P>
<P><A HREF='SYSMNU.asp'>Desktop</A></P>
<P><A HREF='SYSMNU.asp'>Servers</A></P>
<P><A HREF='SYSMNU.asp'>Monitors</A></P>
</DIR>

<B><P>BIOS</P><DIR>
<DIR>

</B><P><A HREF='BIOStbls.asp#Portable'>Portable</A></P>
<P><A HREF='BIOStbls.asp#Bravo'>Bravo</A></P>
<P><A HREF='BIOStbls.asp#Advantage'>Advantage!</A></P>
<P><A HREF='BIOStbls.asp#Premmia'>Premmia</A></P>
<P><A HREF='BIOStbls.asp#Premium'>Premium</A></P>
<P><A HREF='BIOStbls.asp#Manhattan'>Manhattan</A></P></DIR>
</DIR>

<B><P>ASC</P><DIR>
<DIR>

</B><P><A HREF='ASCMNU.asp'>Canada</A></P>
<P><A HREF='ASCMNU.asp'>USA</A></P>
<P><A HREF='ASCMNU.asp'>Latin America</A></P></DIR>
</DIR>

<B><P>Tech Ref</P><DIR>
<DIR>

</B><P><A HREF='TREFMNU.asp'>Software</A></P>
<P><A HREF='TREFMNU.asp'>Technical</A></P>
<P><A HREF='TREFMNU.asp'>Information</A></P></DIR>
</DIR>

<B><P>News</P><DIR>
<DIR>

<P><A HREF='NEWMNU.asp'>Pronto!Pro</B><I>Online</I> News</A></P>
<P><A HREF='NEWMNU.asp'>AST Computer News</A></P></DIR>
</DIR>

<B><P>Help</P><DIR>
<DIR>

</B><P>Interface tutorial</P>
<P>Toolbar</P>
<P>Step By Step Instructions</P>
<P>Site Map</P></DIR>
</DIR>

<B><P>Tools</P>
<DIR>
</B><P><A HREF='TOOLS.asp'>Software Tools</A></P>
<P><A HREF='TOOLS.asp'>Links</A></P></DIR>
</DIR>

<B><P><A HREF='FEED.ASP'>Feedback</A></P>
</B><P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P></BODY>
</HTML>
