<html>
<head>
<title>News Menu</title>
</head>

<body bgcolor='ffffff' text='000000' LINK="#0000FF" ALINK="#0000FF" VLINK="#0000FF"><b>
Pronto! Pro <i>OnLine</I> Text Version
<CENTER>
<!-- #INCLUDE FILE="TITLE.INC" -->
</CENTER>
<P>

<CENTER><H2>Pronto! Pro NEWS</H2>
<A HREF="http://www.ast.com/ast/newsroom/press_list.asp">AST News room</A></TD>
</CENTER>
<HR>

<H3>News August 22, 1997</H3>
<B>Added systems:</B>
<BR>No New Systems
<P>
<B>Technical Reference Library - Additions and Updates</B>
<BR>No New Documents 
<HR>
<P>
<H3> News August 15, 1997  </H3>
<B>Added systems:</B>
<BR>503457 Advantage! + P200
<P>
<B>Technical Reference Library - Additions and Updates </B>
<BR>TB1751 New Ascentia A+, Windows 95, Battery Icon
<BR>TB1750 New Bravo LC, 3COM 3C509 &amp; SB16 PnP CT2940
<BR>TB1749 New ESS1788 Drivers and AST Adventure! 4xx
<BR>TB1748 New Ascentia A Plus and Minidock
<BR>TB1737 New Ascentia A and Memory Upgrade Issue
<BR>SB0431 New 3Com EtherDisk XL Ethernet Driver,v1.00
<BR>SB0430 New HD Restore Adv! 7312, v1.00 Ireland
<BR>SB0314 Update Advantage! 4xx System BIOS v1.04 China
<BR>SB0312 Update Bravo MS/MS-T System BIOS, v1.00.12
<BR>IB0049 New Ascentia A+, Floppy Drive Access

<HR>
<P>
<H3> News August 8, 1997 </H3>
<B>Added systems:</B>
<BR>503452 Bravo EL 5166
<P>
<B>Technical Reference Library - Additions and Updates</B>
<BR>TB1746 New OS/2 and Hard Disk Limitation
<BR>TB1743 New Advantage! 4xx Blue Line Corruption
<BR>SB0328 Update Advantage! 93xx USB BIOS, v1.00.06
<BR>SB0314 Update Advantage! 4xx System BIOS v1.04
<BR>FCN0144 Update Bravo LC System BIOS, Version 2.02
<BR>IB0048 New Windows 95 Joystick Calibration Issue

<HR>
<P>
<H3> News August 1, 1997  </H3>
<B>Added systems:</B>
<BR>No New Systems
<P>
<B>Technical Reference Library - Additions and Updates</B>
<BR>TB1745 New LANDesk and Add-In Adapters 
<BR>TB1742 New Simultaneous Display Functionality
<BR>TB1741 New Bravo MS-T Win95 Sound Device Conflict
<BR>TB1731 New Manhattan S Fails with EISA SCSI Ctrls
<BR>SB0429 New Crystal Audio Disk Patch, Asc A+, v1.00
<BR>SB0427 Update Bravo MS Hard Disk Restore, v1.00
<BR>SB0426 Update ESS1868 Audio Drivers, Release 1.01
<BR>SB0416 Update Docking Station Drivers, v1.20
<BR>SB0415 Update Ascentia A+ Hard Disk Restore, v1.01
<BR>SB0411 Update Bravo LC 6233 Flash BIOS, V1.00.02
<BR>SB0402 Update Bravo MS, Bravo LC System BIOS, v1.04
<BR>SB0390 Update Manh D6200, Presence Pro BIOS v1.00.04
<BR>SB0380 Update Manhattan S/CommercePro BIOS, v1.40
<BR>SB0312 Update Bravo MS/MS-T System BIOS, v1.00.12
<BR>SB0305 Update Manhattan S6200, CommercePro BIOS v3.90
<BR>FCN0144 Update Bravo LC System BIOS, Version 2.02
<BR>IB0047 Update Ascentia P and Data Race Internal Modem
<BR>IB0046 Update Crystal 3D Sound Icon Functionality
<BR>IB0045 Update ISACU and AST Commercial Systems
<BR>IB0044 Update Ascentia A+ BIOS
<BR>IB0043 Update Ascentia A BIOS

<HR>
<P>
<H3> July 18, 1997 CD-ROM Production Release (August '97) </H3>
<B>Added systems:</B>
<BR>501766 Advantage! 613E
<BR>501545 8060P European Models
<P>
<B>Technical Reference Library - Additions and Updates</B>
<BR>TB1740 New Bravo MS Win95-SR2 Enhanced ATI Drivers
<BR>TB1660 Update Manhattan S6200 and Adaptec 2940UW
<BR>SB0428 New ATI Mach64 Win95,WinNT Video Drvs,v1.00

<HR>
<P>
<H3> July 11, 1997  </H3>
<B>Added:</B>
<BR>Documentation Kit part numbers for Advantage! and Adventure systems
<BR>IRQ13 to all systems resource listing

<HR>
<P>
<H3> July 4, 1997  </H3>
<B>Added:</B>
<BR>503190 Bravo LC 5133
<BR>503191 Bravo LC / MS-C 5166
<BR>503192 Bravo LC / MS-C 5200
<BR>503340 Bravo LC / MS-C 5166M
<BR>503415 Sabre LC 5133
<BR>503416 Sabre LC 5166
<P>
<B>Technical Reference Library - Additions and Updates</B>
<BR>TB1739 New Ascentia J40 and Xircom PC Cards
<BR>TB1738 New HP 5L May Not Go into &quot;SleepMode&quot; 
<BR>TB1736 New Bravo/LANDesk &amp; BIOS Data Access Error
<BR>TB1734 New Adaptec 7800 &amp; Missing Operating System
<BR>TB1385 Update Adv! Win95 ASTWorks II &amp; Phone Center
<BR>TB1165 Update Manhattan P &amp; V and PCI Bridge Support
<BR>SB0424 New AST Adv! Hong Kong HD Restore, v1.00
<BR>SB0422 New AST Adventure! French HDRestore, v 1.00
<BR>SB0367 Update Advantage! 6xx/8xx Flash BIOS, v1.00.13<BR>




</body>
</html>
