<html><head>
<title>Systems Menu</title>
</head>
<body bgcolor='ffffff' text='000000' LINK="#0000FF" ALINK="#0000FF" VLINK="#0000FF"><b>
Pronto! Pro <i>OnLine</I> Text Version
</b>
<CENTER>
<!-- #INCLUDE FILE="TITLE.INC" -->
</CENTER>
<P>

<FORM METHOD=POST ACTION='DSPPAGES/SYSTEMS.asp?'>
<b>System Search P/N: <INPUT TYPE='TEXT' SIZE='12' NAME='PN'></b>
</FORM>


<table border="3" width="100%">
    <tr>
        <td><h3 align="center"><a href="#ADV">Advantage!</a></h3></td>
        <td><h3 align="center"><a href="#PORT">Portables </a></h3></td>
        <td><h3 align="center"><a href="#DES">Desktops </a></h3></td>
        <td><h3 align="center"><a href="#SER">Servers </a></h3></td>
        <td><h3 align="center"><a href="monitors.asp">Monitors </a></h3></td>
    </tr><tr>
        <td><h3 align="center">TBA</h3></td>
        <td><h3 align="center">TBA</a></h3></td>
        <td><h3 align="center">TBA</a></h3></td>
        <td><h3 align="center"><a href="../3rd/srvopt.htm">Certified 3rd<br>Party Options </a></h3></td>
        <td><h3 align="center"></a></h3></td>
    </tr>

</table>
<hr>
<h2 align="center"><a name="ADV">Advantage! </a></h2>

<table border="0" width="100%">
    <tr>
        <td><a href="adv/ADV200.asp#sys">Adventure! 200 </a></td>
        <td><a href="adv/ADV400.asp#sys">Adventure! 400 </a></td>
        <td><a href="adv/ADV600.asp#sys">Advantage! 600 </a></td>
    </tr>
    <tr>
        <td><a href="adv/ADV800.asp#sys">Advantage! 800 </a></td>
        <td><a href="adv/ADV2K.asp#sys">Advantage! 2000 </a></td>
        <td><a href="adv/ADV4k.asp#sys">Advantage! 4000 </a></td>
 
   </tr>
    <tr>
        <td><a href="adv/ADV6K.asp#sys">Advantage! 6000 </a></td>
        <td><a href="adv/ADV8k.asp#sys">Advantage! 8000 </a></td>
        <td><a href="adv/ADV73K.asp#sys">Advantage! 7300 </a></td>
    </tr>
    <tr>
        <td><a href="adv/ADV74K.asp#sys">Advantage! 7400 </a></td>
        <td><a href="adv/ADV93K.asp#sys">Advantage! 9300 </a></td>
        <td><a href="adv/ADV94K.asp#sys">Advantage! 9400 </a></td>
    </tr>
    <tr>
        <td><a href="adv/ADV94.asp#sys">  Advantage! ('94) </a></td>
        <td><a href="adv/ADVPCHI.asp#sys">Advantage! Plus (China) </a></td>
        <td><a href="adv/ADVPMT.asp#sys"> Adventure Plus MT </a></td>
    </tr>
    <tr>
        <td><a href="adv/ADVPRO.asp#sys"> Advantage! Pro </a></td>
        <td><a href="adv/ADVADV.asp#sys">Adv! Adventure </a></td>
        <td><a href="adv/ADVofi.asp#sys">Ofi - Master </a></td>
    </tr>
    <tr>
        <td><a href="adv/ADVmas.asp#sys">M - Master </a></td>
        <td><a href="adv/advexp.asp#sys">Advantage! EXP </a></td>
        <td><a href="adv/ADVpls.asp#sys">Advantage! Plus</a></td>
    </tr>
</table>

<p align="center"><a href="#TOP">Top</a> </p>

<hr>

<h2 align="center"><a name="PORT">Portables </a></h2>

<table border="0" width="100%">
    <tr>
        <td><a href="port/ascm.asp">Ascentia M</a> </td>
        <td><a href="port/ascp.asp">Ascentia P</a> </td>
        <td><a href="port/ascj.asp">Ascentia J</a> </td>
    </tr>
    <tr>
        <td><a href="port/asca.asp">Ascentia A</a> </td>	
        <td><a href="port/sen500.asp">SensPro 500</a> </td>
        <td><a href="port/asc950.asp">Ascentia 950</a> </td>
    </tr>
    <tr>
        <td><a href="port/asc910.asp">Ascentia 910</a> </td>	
        <td><a href="port/asc900.asp">Ascentia 900</a> </td>
        <td><a href="port/asc810.asp">Ascentia 810</a> </td>
    </tr>
    <tr>
	    <td><a href="port/asc800.asp">Ascentia 800</a> </td>
        <td><a href="port/pexec.asp">PowerExec </a></td>
        <td><a href="port/advexp.asp">Advantage! Explorer</a> </td>
    </tr>
    <tr>
        <td><a href="port/advnb.asp">Advantage! NB </a></td>	
        <td><a href="port/nbrc.asp">Bravo NB-RC</a> </td>
        <td><a href="port/branb.asp">Bravo NB </a></td>

    </tr>
</table>
<p align="center"><a href="#TOP">Top</a> </p>
<hr>
<h2 align="center"><a name="DES">Desktops</a></h2>
<table border="0" width="100%">
    <tr>
        <td><a href="des/bmsd.asp">Bravo MS Desktop </a></td>
        <td><a href="des/bmsmt.asp">Bravo MS MiniTower </a></td>
        <td><a href="des/blcmsc.asp">Bravo LC/MS-C </a></td>
    </tr>
    <tr>
        <td><a href="des/Sablc.asp">Saber LC </a></td>
        <td><a href="des/bmst.asp">Bravo MS-T </a></td>
        <td><a href="des/bms.asp">Bravo MS </a></td>
    </tr>
    <tr>
        <td><a href="des/bmspro.asp">Bravo MS Pro </a></td>
        <td><a href="des/bmsl.asp">Bravo MS L </a></td>
        <td><a href="des/blc5k.asp">Bravo LC 5000</a> </td>
    </tr>
    <tr>
        <td><a href="des/blckp.asp">Bravo LC (King P) </a></td>
        <td><a href="des/blck.asp">Bravo LC (King) </a></td>
        <td><a href="des/blp.asp">Bravo LP </a></td>
    </tr>
    <tr>
        <td><a href="des/blc2.asp">Bravo LC (LC2) </a></td>
        <td><a href="des/blc.asp">Bravo (LC) </a></td>
        <td><a href="des/bmt.asp">Bravo MT </a></td>
    </tr>
    <tr>
        <td><a href="des/pragx.asp">Premmia GX </a></td>
        <td><a href="des/pramte.asp">Premmia MTE </a></td>
        <td><a href="des/prase.asp">Premmia SE </a></td>
    </tr>
    <tr>
        <td><a href="des/pramx.asp">Premmia MX </a></td>
        <td><a href="des/pralx.asp">Premmia LX </a></td>
        <td><a href="des/pra.asp">Premmia </a></td>
    </tr>
    <tr>
        <td><a href="des/prm3pl.asp">Premium III+ (China) </a></td>
        <td><a href="des/prmpro.asp">Premium Pro (China) </a></td>
        <td><a href="des/Prm3.asp">Premium III (China) </a></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
</table>

<p align="center"><a href="#TOP">Top</centre></a></p>

<hr>

<h1 align="center"><a name="SER">Servers</a></h1>
<div align="center"><center>

<table border="0" width="100%">
    <tr>
        <td><a href="ser/preks.asp">Premium KS</a></td>
        <td><a href="ser/mppro.asp">Manhattan Presence PRO </a></td>
        <td><a href="ser/mcpro.asp">Manhattan Commerce PRO </a></td>
    </tr>
    <tr>
	    <td><a href="ser/mans.asp">Manhattan S </a></td>
        <td><a href="ser/manp.asp">Manhattan P </a></td>
        <td><a href="ser/mand.asp">Manhattan D </a></td>

    </tr>
    <tr>
        <td><a href="ser/manv.asp">Manhattan V </a></td>	
        <td><a href="ser/mang.asp">Manhattan G</a> </td>
        <td><a href="ser/%20.asp"></a> </td>
    </tr>
</table>
</center></div>

<p align="center"><a href="#TOP">Top</a> </p>

</body>
</html>
